// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookings.sql

package queries

import (
	"context"
	"database/sql"
)

const addBookingPet = `-- name: AddBookingPet :exec
INSERT INTO booking_pets (
	booking_id,
	pet_id,
	notes
)
VALUES (?, ?, ?)
ON CONFLICT (booking_id, pet_id) DO UPDATE SET
	notes = excluded.notes
`

type AddBookingPetParams struct {
	BookingID string         `json:"booking_id"`
	PetID     string         `json:"pet_id"`
	Notes     sql.NullString `json:"notes"`
}

func (q *Queries) AddBookingPet(ctx context.Context, arg AddBookingPetParams) error {
	_, err := q.db.ExecContext(ctx, addBookingPet, arg.BookingID, arg.PetID, arg.Notes)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
	id,
	household_id,
	service_type,
	status,
	start_at,
	end_at,
	location_type,
	address_snapshot,
	requested_by_contact_id,
	assigned_staff_id,
	source,
	notes,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, household_id, service_type, status, start_at, end_at, location_type, address_snapshot, requested_by_contact_id, assigned_staff_id, source, notes, completed_at, cancelled_at, created_at, updated_at
`

type CreateBookingParams struct {
	ID                   string         `json:"id"`
	HouseholdID          string         `json:"household_id"`
	ServiceType          string         `json:"service_type"`
	Status               string         `json:"status"`
	StartAt              string         `json:"start_at"`
	EndAt                sql.NullString `json:"end_at"`
	LocationType         string         `json:"location_type"`
	AddressSnapshot      sql.NullString `json:"address_snapshot"`
	RequestedByContactID sql.NullString `json:"requested_by_contact_id"`
	AssignedStaffID      sql.NullString `json:"assigned_staff_id"`
	Source               string         `json:"source"`
	Notes                sql.NullString `json:"notes"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.ID,
		arg.HouseholdID,
		arg.ServiceType,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.LocationType,
		arg.AddressSnapshot,
		arg.RequestedByContactID,
		arg.AssignedStaffID,
		arg.Source,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ServiceType,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.LocationType,
		&i.AddressSnapshot,
		&i.RequestedByContactID,
		&i.AssignedStaffID,
		&i.Source,
		&i.Notes,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookingPets = `-- name: DeleteBookingPets :exec
DELETE FROM booking_pets
WHERE booking_id = ?
`

func (q *Queries) DeleteBookingPets(ctx context.Context, bookingID string) error {
	_, err := q.db.ExecContext(ctx, deleteBookingPets, bookingID)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT id, household_id, service_type, status, start_at, end_at, location_type, address_snapshot, requested_by_contact_id, assigned_staff_id, source, notes, completed_at, cancelled_at, created_at, updated_at
FROM bookings
WHERE id = ?
`

func (q *Queries) GetBooking(ctx context.Context, id string) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ServiceType,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.LocationType,
		&i.AddressSnapshot,
		&i.RequestedByContactID,
		&i.AssignedStaffID,
		&i.Source,
		&i.Notes,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingPets = `-- name: ListBookingPets :many
SELECT
	bp.booking_id,
	bp.pet_id,
	bp.notes,
	p.name,
	p.species
FROM booking_pets AS bp
JOIN pets AS p ON p.id = bp.pet_id
WHERE bp.booking_id = ?
ORDER BY p.name
`

type ListBookingPetsRow struct {
	BookingID string         `json:"booking_id"`
	PetID     string         `json:"pet_id"`
	Notes     sql.NullString `json:"notes"`
	Name      string         `json:"name"`
	Species   string         `json:"species"`
}

func (q *Queries) ListBookingPets(ctx context.Context, bookingID string) ([]ListBookingPetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingPets, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingPetsRow
	for rows.Next() {
		var i ListBookingPetsRow
		if err := rows.Scan(
			&i.BookingID,
			&i.PetID,
			&i.Notes,
			&i.Name,
			&i.Species,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT id, household_id, service_type, status, start_at, end_at, location_type, address_snapshot, requested_by_contact_id, assigned_staff_id, source, notes, completed_at, cancelled_at, created_at, updated_at
FROM bookings
ORDER BY start_at, created_at
`

func (q *Queries) ListBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ServiceType,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.LocationType,
			&i.AddressSnapshot,
			&i.RequestedByContactID,
			&i.AssignedStaffID,
			&i.Source,
			&i.Notes,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByHousehold = `-- name: ListBookingsByHousehold :many
SELECT id, household_id, service_type, status, start_at, end_at, location_type, address_snapshot, requested_by_contact_id, assigned_staff_id, source, notes, completed_at, cancelled_at, created_at, updated_at
FROM bookings
WHERE household_id = ?
ORDER BY start_at DESC, created_at DESC
`

func (q *Queries) ListBookingsByHousehold(ctx context.Context, householdID string) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ServiceType,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.LocationType,
			&i.AddressSnapshot,
			&i.RequestedByContactID,
			&i.AssignedStaffID,
			&i.Source,
			&i.Notes,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByRange = `-- name: ListBookingsByRange :many
SELECT id, household_id, service_type, status, start_at, end_at, location_type, address_snapshot, requested_by_contact_id, assigned_staff_id, source, notes, completed_at, cancelled_at, created_at, updated_at
FROM bookings
WHERE start_at >= ? AND start_at < ?
ORDER BY start_at, created_at
`

type ListBookingsByRangeParams struct {
	StartAt   string `json:"start_at"`
	StartAt_2 string `json:"start_at_2"`
}

func (q *Queries) ListBookingsByRange(ctx context.Context, arg ListBookingsByRangeParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByRange, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ServiceType,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.LocationType,
			&i.AddressSnapshot,
			&i.RequestedByContactID,
			&i.AssignedStaffID,
			&i.Source,
			&i.Notes,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET
	household_id = ?,
	service_type = ?,
	status = ?,
	start_at = ?,
	end_at = ?,
	location_type = ?,
	address_snapshot = ?,
	requested_by_contact_id = ?,
	assigned_staff_id = ?,
	source = ?,
	notes = ?,
	completed_at = ?,
	cancelled_at = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, household_id, service_type, status, start_at, end_at, location_type, address_snapshot, requested_by_contact_id, assigned_staff_id, source, notes, completed_at, cancelled_at, created_at, updated_at
`

type UpdateBookingParams struct {
	HouseholdID          string         `json:"household_id"`
	ServiceType          string         `json:"service_type"`
	Status               string         `json:"status"`
	StartAt              string         `json:"start_at"`
	EndAt                sql.NullString `json:"end_at"`
	LocationType         string         `json:"location_type"`
	AddressSnapshot      sql.NullString `json:"address_snapshot"`
	RequestedByContactID sql.NullString `json:"requested_by_contact_id"`
	AssignedStaffID      sql.NullString `json:"assigned_staff_id"`
	Source               string         `json:"source"`
	Notes                sql.NullString `json:"notes"`
	CompletedAt          sql.NullString `json:"completed_at"`
	CancelledAt          sql.NullString `json:"cancelled_at"`
	UpdatedAt            string         `json:"updated_at"`
	ID                   string         `json:"id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.HouseholdID,
		arg.ServiceType,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.LocationType,
		arg.AddressSnapshot,
		arg.RequestedByContactID,
		arg.AssignedStaffID,
		arg.Source,
		arg.Notes,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ServiceType,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.LocationType,
		&i.AddressSnapshot,
		&i.RequestedByContactID,
		&i.AssignedStaffID,
		&i.Source,
		&i.Notes,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
