// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: care_tasks.sql

package queries

import (
	"context"
	"database/sql"
)

const createCareTask = `-- name: CreateCareTask :one
INSERT INTO care_tasks (
	id,
	booking_id,
	household_id,
	pet_id,
	task_type,
	title,
	instructions,
	due_at,
	status,
	assigned_staff_id,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
`

type CreateCareTaskParams struct {
	ID              string         `json:"id"`
	BookingID       sql.NullString `json:"booking_id"`
	HouseholdID     string         `json:"household_id"`
	PetID           sql.NullString `json:"pet_id"`
	TaskType        string         `json:"task_type"`
	Title           string         `json:"title"`
	Instructions    sql.NullString `json:"instructions"`
	DueAt           sql.NullString `json:"due_at"`
	Status          string         `json:"status"`
	AssignedStaffID sql.NullString `json:"assigned_staff_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) CreateCareTask(ctx context.Context, arg CreateCareTaskParams) (CareTask, error) {
	row := q.db.QueryRowContext(ctx, createCareTask,
		arg.ID,
		arg.BookingID,
		arg.HouseholdID,
		arg.PetID,
		arg.TaskType,
		arg.Title,
		arg.Instructions,
		arg.DueAt,
		arg.Status,
		arg.AssignedStaffID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CareTask
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.HouseholdID,
		&i.PetID,
		&i.TaskType,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.Status,
		&i.AssignedStaffID,
		&i.CompletedAt,
		&i.CompletedByStaffID,
		&i.SkippedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCareTask = `-- name: GetCareTask :one
SELECT id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
FROM care_tasks
WHERE id = ?
`

func (q *Queries) GetCareTask(ctx context.Context, id string) (CareTask, error) {
	row := q.db.QueryRowContext(ctx, getCareTask, id)
	var i CareTask
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.HouseholdID,
		&i.PetID,
		&i.TaskType,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.Status,
		&i.AssignedStaffID,
		&i.CompletedAt,
		&i.CompletedByStaffID,
		&i.SkippedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCareTasks = `-- name: ListCareTasks :many
SELECT id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
FROM care_tasks
ORDER BY due_at, created_at
`

func (q *Queries) ListCareTasks(ctx context.Context) ([]CareTask, error) {
	rows, err := q.db.QueryContext(ctx, listCareTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareTask
	for rows.Next() {
		var i CareTask
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.HouseholdID,
			&i.PetID,
			&i.TaskType,
			&i.Title,
			&i.Instructions,
			&i.DueAt,
			&i.Status,
			&i.AssignedStaffID,
			&i.CompletedAt,
			&i.CompletedByStaffID,
			&i.SkippedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCareTasksByBooking = `-- name: ListCareTasksByBooking :many
SELECT id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
FROM care_tasks
WHERE booking_id = ?
ORDER BY due_at, created_at
`

func (q *Queries) ListCareTasksByBooking(ctx context.Context, bookingID sql.NullString) ([]CareTask, error) {
	rows, err := q.db.QueryContext(ctx, listCareTasksByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareTask
	for rows.Next() {
		var i CareTask
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.HouseholdID,
			&i.PetID,
			&i.TaskType,
			&i.Title,
			&i.Instructions,
			&i.DueAt,
			&i.Status,
			&i.AssignedStaffID,
			&i.CompletedAt,
			&i.CompletedByStaffID,
			&i.SkippedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCareTasksByHousehold = `-- name: ListCareTasksByHousehold :many
SELECT id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
FROM care_tasks
WHERE household_id = ?
ORDER BY due_at, created_at
`

func (q *Queries) ListCareTasksByHousehold(ctx context.Context, householdID string) ([]CareTask, error) {
	rows, err := q.db.QueryContext(ctx, listCareTasksByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareTask
	for rows.Next() {
		var i CareTask
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.HouseholdID,
			&i.PetID,
			&i.TaskType,
			&i.Title,
			&i.Instructions,
			&i.DueAt,
			&i.Status,
			&i.AssignedStaffID,
			&i.CompletedAt,
			&i.CompletedByStaffID,
			&i.SkippedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCareTasksByRange = `-- name: ListCareTasksByRange :many
SELECT id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
FROM care_tasks
WHERE due_at >= ? AND due_at < ?
ORDER BY due_at, created_at
`

type ListCareTasksByRangeParams struct {
	DueAt   sql.NullString `json:"due_at"`
	DueAt_2 sql.NullString `json:"due_at_2"`
}

func (q *Queries) ListCareTasksByRange(ctx context.Context, arg ListCareTasksByRangeParams) ([]CareTask, error) {
	rows, err := q.db.QueryContext(ctx, listCareTasksByRange, arg.DueAt, arg.DueAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareTask
	for rows.Next() {
		var i CareTask
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.HouseholdID,
			&i.PetID,
			&i.TaskType,
			&i.Title,
			&i.Instructions,
			&i.DueAt,
			&i.Status,
			&i.AssignedStaffID,
			&i.CompletedAt,
			&i.CompletedByStaffID,
			&i.SkippedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCareTask = `-- name: UpdateCareTask :one
UPDATE care_tasks
SET
	booking_id = ?,
	household_id = ?,
	pet_id = ?,
	task_type = ?,
	title = ?,
	instructions = ?,
	due_at = ?,
	status = ?,
	assigned_staff_id = ?,
	completed_at = ?,
	completed_by_staff_id = ?,
	skipped_reason = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, booking_id, household_id, pet_id, task_type, title, instructions, due_at, status, assigned_staff_id, completed_at, completed_by_staff_id, skipped_reason, created_at, updated_at
`

type UpdateCareTaskParams struct {
	BookingID          sql.NullString `json:"booking_id"`
	HouseholdID        string         `json:"household_id"`
	PetID              sql.NullString `json:"pet_id"`
	TaskType           string         `json:"task_type"`
	Title              string         `json:"title"`
	Instructions       sql.NullString `json:"instructions"`
	DueAt              sql.NullString `json:"due_at"`
	Status             string         `json:"status"`
	AssignedStaffID    sql.NullString `json:"assigned_staff_id"`
	CompletedAt        sql.NullString `json:"completed_at"`
	CompletedByStaffID sql.NullString `json:"completed_by_staff_id"`
	SkippedReason      sql.NullString `json:"skipped_reason"`
	UpdatedAt          string         `json:"updated_at"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateCareTask(ctx context.Context, arg UpdateCareTaskParams) (CareTask, error) {
	row := q.db.QueryRowContext(ctx, updateCareTask,
		arg.BookingID,
		arg.HouseholdID,
		arg.PetID,
		arg.TaskType,
		arg.Title,
		arg.Instructions,
		arg.DueAt,
		arg.Status,
		arg.AssignedStaffID,
		arg.CompletedAt,
		arg.CompletedByStaffID,
		arg.SkippedReason,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CareTask
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.HouseholdID,
		&i.PetID,
		&i.TaskType,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.Status,
		&i.AssignedStaffID,
		&i.CompletedAt,
		&i.CompletedByStaffID,
		&i.SkippedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
