// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: charges.sql

package queries

import (
	"context"
	"database/sql"
)

const createCharge = `-- name: CreateCharge :one
INSERT INTO charges (
	id,
	household_id,
	booking_id,
	description,
	amount_minor,
	currency,
	status,
	due_date,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
`

type CreateChargeParams struct {
	ID          string         `json:"id"`
	HouseholdID string         `json:"household_id"`
	BookingID   sql.NullString `json:"booking_id"`
	Description string         `json:"description"`
	AmountMinor int64          `json:"amount_minor"`
	Currency    string         `json:"currency"`
	Status      string         `json:"status"`
	DueDate     sql.NullString `json:"due_date"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) (Charge, error) {
	row := q.db.QueryRowContext(ctx, createCharge,
		arg.ID,
		arg.HouseholdID,
		arg.BookingID,
		arg.Description,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.BookingID,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharge = `-- name: GetCharge :one
SELECT id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
FROM charges
WHERE id = ?
`

func (q *Queries) GetCharge(ctx context.Context, id string) (Charge, error) {
	row := q.db.QueryRowContext(ctx, getCharge, id)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.BookingID,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharges = `-- name: ListCharges :many
SELECT id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
FROM charges
ORDER BY due_date IS NULL, due_date, created_at
`

func (q *Queries) ListCharges(ctx context.Context) ([]Charge, error) {
	rows, err := q.db.QueryContext(ctx, listCharges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Charge
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.BookingID,
			&i.Description,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargesByHousehold = `-- name: ListChargesByHousehold :many
SELECT id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
FROM charges
WHERE household_id = ?
ORDER BY due_date IS NULL, due_date, created_at
`

func (q *Queries) ListChargesByHousehold(ctx context.Context, householdID string) ([]Charge, error) {
	rows, err := q.db.QueryContext(ctx, listChargesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Charge
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.BookingID,
			&i.Description,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCharges = `-- name: ListOpenCharges :many
SELECT id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
FROM charges
WHERE status IN ('unpaid', 'partially_paid')
ORDER BY due_date IS NULL, due_date, created_at
`

func (q *Queries) ListOpenCharges(ctx context.Context) ([]Charge, error) {
	rows, err := q.db.QueryContext(ctx, listOpenCharges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Charge
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.BookingID,
			&i.Description,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshChargeStatus = `-- name: RefreshChargeStatus :one
UPDATE charges
SET
	status = CASE
		WHEN COALESCE((SELECT SUM(amount_minor) FROM payment_allocations WHERE charge_id = charges.id), 0) = 0 THEN 'unpaid'
		WHEN COALESCE((SELECT SUM(amount_minor) FROM payment_allocations WHERE charge_id = charges.id), 0) < amount_minor THEN 'partially_paid'
		ELSE 'paid'
	END,
	updated_at = ?
WHERE charges.id = ?
RETURNING id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
`

type RefreshChargeStatusParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RefreshChargeStatus(ctx context.Context, arg RefreshChargeStatusParams) (Charge, error) {
	row := q.db.QueryRowContext(ctx, refreshChargeStatus, arg.UpdatedAt, arg.ID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.BookingID,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharge = `-- name: UpdateCharge :one
UPDATE charges
SET
	household_id = ?,
	booking_id = ?,
	description = ?,
	amount_minor = ?,
	currency = ?,
	status = ?,
	due_date = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, household_id, booking_id, description, amount_minor, currency, status, due_date, created_at, updated_at
`

type UpdateChargeParams struct {
	HouseholdID string         `json:"household_id"`
	BookingID   sql.NullString `json:"booking_id"`
	Description string         `json:"description"`
	AmountMinor int64          `json:"amount_minor"`
	Currency    string         `json:"currency"`
	Status      string         `json:"status"`
	DueDate     sql.NullString `json:"due_date"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCharge(ctx context.Context, arg UpdateChargeParams) (Charge, error) {
	row := q.db.QueryRowContext(ctx, updateCharge,
		arg.HouseholdID,
		arg.BookingID,
		arg.Description,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.DueDate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.BookingID,
		&i.Description,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
