// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contact_identities.sql

package queries

import (
	"context"
	"database/sql"
)

const contactBelongsToHousehold = `-- name: ContactBelongsToHousehold :one
SELECT EXISTS (
	SELECT 1
	FROM household_contacts
	WHERE contact_id = ? AND household_id = ?
) AS belongs
`

type ContactBelongsToHouseholdParams struct {
	ContactID   string `json:"contact_id"`
	HouseholdID string `json:"household_id"`
}

func (q *Queries) ContactBelongsToHousehold(ctx context.Context, arg ContactBelongsToHouseholdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, contactBelongsToHousehold, arg.ContactID, arg.HouseholdID)
	var belongs int64
	err := row.Scan(&belongs)
	return belongs, err
}

const createContactChannelIdentity = `-- name: CreateContactChannelIdentity :one
INSERT INTO contact_channel_identities (
	id, contact_id, channel, external_user_id, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (contact_id, channel, external_user_id) DO UPDATE SET
	updated_at = excluded.updated_at
RETURNING id, contact_id, channel, external_user_id, created_at, updated_at
`

type CreateContactChannelIdentityParams struct {
	ID             string `json:"id"`
	ContactID      string `json:"contact_id"`
	Channel        string `json:"channel"`
	ExternalUserID string `json:"external_user_id"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) CreateContactChannelIdentity(ctx context.Context, arg CreateContactChannelIdentityParams) (ContactChannelIdentity, error) {
	row := q.db.QueryRowContext(ctx, createContactChannelIdentity,
		arg.ID,
		arg.ContactID,
		arg.Channel,
		arg.ExternalUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ContactChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Channel,
		&i.ExternalUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByChannelIdentity = `-- name: GetContactByChannelIdentity :one
SELECT c.id, c.display_name, c.phone, c.whatsapp_id, c.telegram_id, c.email, c.notes, c.active, c.created_at, c.updated_at
FROM contacts AS c
JOIN contact_channel_identities AS identity ON identity.contact_id = c.id
WHERE identity.channel = ? AND identity.external_user_id = ? AND c.active = 1
LIMIT 1
`

type GetContactByChannelIdentityParams struct {
	Channel        string `json:"channel"`
	ExternalUserID string `json:"external_user_id"`
}

func (q *Queries) GetContactByChannelIdentity(ctx context.Context, arg GetContactByChannelIdentityParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContactByChannelIdentity, arg.Channel, arg.ExternalUserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactHouseholdPets = `-- name: ListContactHouseholdPets :many
SELECT p.household_id, p.id AS pet_id, p.name AS pet_name
FROM pets AS p
JOIN household_contacts AS hc ON hc.household_id = p.household_id
JOIN households AS h ON h.id = p.household_id
WHERE hc.contact_id = ? AND p.active = 1 AND h.active = 1
ORDER BY p.household_id, p.name
`

type ListContactHouseholdPetsRow struct {
	HouseholdID string `json:"household_id"`
	PetID       string `json:"pet_id"`
	PetName     string `json:"pet_name"`
}

func (q *Queries) ListContactHouseholdPets(ctx context.Context, contactID string) ([]ListContactHouseholdPetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactHouseholdPets, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactHouseholdPetsRow
	for rows.Next() {
		var i ListContactHouseholdPetsRow
		if err := rows.Scan(&i.HouseholdID, &i.PetID, &i.PetName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactHouseholdResolutionOptions = `-- name: ListContactHouseholdResolutionOptions :many
SELECT DISTINCT hc.contact_id, h.id AS household_id, h.display_name AS household_name
FROM household_contacts AS hc
JOIN households AS h ON h.id = hc.household_id
WHERE h.active = 1
ORDER BY h.display_name
`

type ListContactHouseholdResolutionOptionsRow struct {
	ContactID     string `json:"contact_id"`
	HouseholdID   string `json:"household_id"`
	HouseholdName string `json:"household_name"`
}

func (q *Queries) ListContactHouseholdResolutionOptions(ctx context.Context) ([]ListContactHouseholdResolutionOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactHouseholdResolutionOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactHouseholdResolutionOptionsRow
	for rows.Next() {
		var i ListContactHouseholdResolutionOptionsRow
		if err := rows.Scan(&i.ContactID, &i.HouseholdID, &i.HouseholdName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsForContactResolution = `-- name: ListHouseholdsForContactResolution :many
SELECT DISTINCT h.id, h.display_name, h.address_line1, h.address_line2, h.neighborhood, h.city, h.timezone, h.notes, h.active, h.created_at, h.updated_at
FROM households AS h
JOIN household_contacts AS hc ON hc.household_id = h.id
WHERE hc.contact_id = ? AND h.active = 1
ORDER BY hc.is_primary DESC, hc.created_at, h.display_name
`

func (q *Queries) ListHouseholdsForContactResolution(ctx context.Context, contactID string) ([]Household, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdsForContactResolution, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Neighborhood,
			&i.City,
			&i.Timezone,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationHouseholdByMessage = `-- name: SetConversationHouseholdByMessage :exec
UPDATE conversations
SET household_id = ?, updated_at = ?
WHERE id = (SELECT conversation_id FROM messages WHERE messages.id = ?)
`

type SetConversationHouseholdByMessageParams struct {
	HouseholdID sql.NullString `json:"household_id"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) SetConversationHouseholdByMessage(ctx context.Context, arg SetConversationHouseholdByMessageParams) error {
	_, err := q.db.ExecContext(ctx, setConversationHouseholdByMessage, arg.HouseholdID, arg.UpdatedAt, arg.ID)
	return err
}

const setDetectedRequestHousehold = `-- name: SetDetectedRequestHousehold :exec
UPDATE detected_requests
SET household_id = ?, updated_at = ?
WHERE id = ?
`

type SetDetectedRequestHouseholdParams struct {
	HouseholdID sql.NullString `json:"household_id"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) SetDetectedRequestHousehold(ctx context.Context, arg SetDetectedRequestHouseholdParams) error {
	_, err := q.db.ExecContext(ctx, setDetectedRequestHousehold, arg.HouseholdID, arg.UpdatedAt, arg.ID)
	return err
}
