// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contacts.sql

package queries

import (
	"context"
	"database/sql"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
	id,
	display_name,
	phone,
	whatsapp_id,
	telegram_id,
	email,
	notes,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
`

type CreateContactParams struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	WhatsappID  sql.NullString `json:"whatsapp_id"`
	TelegramID  sql.NullString `json:"telegram_id"`
	Email       sql.NullString `json:"email"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.ID,
		arg.DisplayName,
		arg.Phone,
		arg.WhatsappID,
		arg.TelegramID,
		arg.Email,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
FROM contacts
WHERE id = ?
`

func (q *Queries) GetContact(ctx context.Context, id string) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkHouseholdContact = `-- name: LinkHouseholdContact :exec
INSERT INTO household_contacts (
	household_id,
	contact_id,
	role,
	is_primary,
	notes,
	created_at
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (household_id, contact_id, role) DO UPDATE SET
	is_primary = excluded.is_primary,
	notes = excluded.notes
`

type LinkHouseholdContactParams struct {
	HouseholdID string         `json:"household_id"`
	ContactID   string         `json:"contact_id"`
	Role        string         `json:"role"`
	IsPrimary   int64          `json:"is_primary"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) LinkHouseholdContact(ctx context.Context, arg LinkHouseholdContactParams) error {
	_, err := q.db.ExecContext(ctx, linkHouseholdContact,
		arg.HouseholdID,
		arg.ContactID,
		arg.Role,
		arg.IsPrimary,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const listContacts = `-- name: ListContacts :many
SELECT id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
FROM contacts
WHERE active = 1
ORDER BY display_name
`

func (q *Queries) ListContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Phone,
			&i.WhatsappID,
			&i.TelegramID,
			&i.Email,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdContacts = `-- name: ListHouseholdContacts :many
SELECT
	hc.household_id,
	hc.contact_id,
	hc.role,
	hc.is_primary,
	hc.notes,
	hc.created_at,
	c.display_name,
	c.phone,
	c.whatsapp_id,
	c.telegram_id,
	c.email
FROM household_contacts AS hc
JOIN contacts AS c ON c.id = hc.contact_id
WHERE hc.household_id = ?
ORDER BY hc.is_primary DESC, c.display_name
`

type ListHouseholdContactsRow struct {
	HouseholdID string         `json:"household_id"`
	ContactID   string         `json:"contact_id"`
	Role        string         `json:"role"`
	IsPrimary   int64          `json:"is_primary"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   string         `json:"created_at"`
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	WhatsappID  sql.NullString `json:"whatsapp_id"`
	TelegramID  sql.NullString `json:"telegram_id"`
	Email       sql.NullString `json:"email"`
}

func (q *Queries) ListHouseholdContacts(ctx context.Context, householdID string) ([]ListHouseholdContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdContacts, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseholdContactsRow
	for rows.Next() {
		var i ListHouseholdContactsRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.ContactID,
			&i.Role,
			&i.IsPrimary,
			&i.Notes,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Phone,
			&i.WhatsappID,
			&i.TelegramID,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET
	display_name = ?,
	phone = ?,
	whatsapp_id = ?,
	telegram_id = ?,
	email = ?,
	notes = ?,
	active = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
`

type UpdateContactParams struct {
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	WhatsappID  sql.NullString `json:"whatsapp_id"`
	TelegramID  sql.NullString `json:"telegram_id"`
	Email       sql.NullString `json:"email"`
	Notes       sql.NullString `json:"notes"`
	Active      int64          `json:"active"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, updateContact,
		arg.DisplayName,
		arg.Phone,
		arg.WhatsappID,
		arg.TelegramID,
		arg.Email,
		arg.Notes,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
