// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: households.sql

package queries

import (
	"context"
	"database/sql"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (
	id,
	display_name,
	address_line1,
	address_line2,
	neighborhood,
	city,
	timezone,
	notes,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, display_name, address_line1, address_line2, neighborhood, city, timezone, notes, active, created_at, updated_at
`

type CreateHouseholdParams struct {
	ID           string         `json:"id"`
	DisplayName  string         `json:"display_name"`
	AddressLine1 sql.NullString `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	Neighborhood sql.NullString `json:"neighborhood"`
	City         sql.NullString `json:"city"`
	Timezone     sql.NullString `json:"timezone"`
	Notes        sql.NullString `json:"notes"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRowContext(ctx, createHousehold,
		arg.ID,
		arg.DisplayName,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Neighborhood,
		arg.City,
		arg.Timezone,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Neighborhood,
		&i.City,
		&i.Timezone,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, display_name, address_line1, address_line2, neighborhood, city, timezone, notes, active, created_at, updated_at
FROM households
WHERE id = ?
`

func (q *Queries) GetHousehold(ctx context.Context, id string) (Household, error) {
	row := q.db.QueryRowContext(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Neighborhood,
		&i.City,
		&i.Timezone,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHouseholds = `-- name: ListHouseholds :many
SELECT id, display_name, address_line1, address_line2, neighborhood, city, timezone, notes, active, created_at, updated_at
FROM households
WHERE active = 1
ORDER BY display_name
`

func (q *Queries) ListHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Neighborhood,
			&i.City,
			&i.Timezone,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET
	display_name = ?,
	address_line1 = ?,
	address_line2 = ?,
	neighborhood = ?,
	city = ?,
	timezone = ?,
	notes = ?,
	active = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, display_name, address_line1, address_line2, neighborhood, city, timezone, notes, active, created_at, updated_at
`

type UpdateHouseholdParams struct {
	DisplayName  string         `json:"display_name"`
	AddressLine1 sql.NullString `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	Neighborhood sql.NullString `json:"neighborhood"`
	City         sql.NullString `json:"city"`
	Timezone     sql.NullString `json:"timezone"`
	Notes        sql.NullString `json:"notes"`
	Active       int64          `json:"active"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRowContext(ctx, updateHousehold,
		arg.DisplayName,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Neighborhood,
		arg.City,
		arg.Timezone,
		arg.Notes,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Neighborhood,
		&i.City,
		&i.Timezone,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
