// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: household_deletion.sql

package queries

import (
	"context"
	"database/sql"
)

const deleteContactIdentitiesIfOtherwiseOrphaned = `-- name: DeleteContactIdentitiesIfOtherwiseOrphaned :exec
DELETE FROM contact_channel_identities
WHERE contact_id = ?1
  AND NOT EXISTS (SELECT 1 FROM household_contacts WHERE contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM bookings WHERE requested_by_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM payments WHERE payer_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM conversations WHERE primary_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM messages WHERE sender_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM detected_requests WHERE contact_id = ?1)
`

func (q *Queries) DeleteContactIdentitiesIfOtherwiseOrphaned(ctx context.Context, contactID string) error {
	_, err := q.db.ExecContext(ctx, deleteContactIdentitiesIfOtherwiseOrphaned, contactID)
	return err
}

const deleteContactIfOrphaned = `-- name: DeleteContactIfOrphaned :exec
DELETE FROM contacts
WHERE id = ?1
  AND NOT EXISTS (SELECT 1 FROM household_contacts WHERE contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM bookings WHERE requested_by_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM payments WHERE payer_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM conversations WHERE primary_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM messages WHERE sender_contact_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM detected_requests WHERE contact_id = ?1)
`

func (q *Queries) DeleteContactIfOrphaned(ctx context.Context, contactID string) error {
	_, err := q.db.ExecContext(ctx, deleteContactIfOrphaned, contactID)
	return err
}

const deleteHouseholdBookingPets = `-- name: DeleteHouseholdBookingPets :exec
DELETE FROM booking_pets
WHERE booking_id IN (SELECT bookings.id FROM bookings WHERE bookings.household_id = ?1)
   OR pet_id IN (SELECT pets.id FROM pets WHERE pets.household_id = ?1)
`

func (q *Queries) DeleteHouseholdBookingPets(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdBookingPets, targetHouseholdID)
	return err
}

const deleteHouseholdBookingSources = `-- name: DeleteHouseholdBookingSources :exec
DELETE FROM booking_sources
WHERE booking_id IN (SELECT bookings.id FROM bookings WHERE bookings.household_id = ?1)
   OR detected_request_id IN (
	SELECT dr.id
	FROM detected_requests AS dr
	WHERE dr.household_id = ?1
	   OR dr.converted_booking_id IN (SELECT bookings.id FROM bookings WHERE bookings.household_id = ?1)
	   OR dr.message_id IN (
		SELECT m.id FROM messages AS m
		JOIN conversations AS c ON c.id = m.conversation_id
		WHERE c.household_id = ?1
	   )
   )
   OR message_id IN (
	SELECT m.id FROM messages AS m
	JOIN conversations AS c ON c.id = m.conversation_id
	WHERE c.household_id = ?1
   )
`

func (q *Queries) DeleteHouseholdBookingSources(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdBookingSources, targetHouseholdID)
	return err
}

const deleteHouseholdBookings = `-- name: DeleteHouseholdBookings :exec
DELETE FROM bookings WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdBookings(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdBookings, targetHouseholdID)
	return err
}

const deleteHouseholdCareRoutines = `-- name: DeleteHouseholdCareRoutines :exec
DELETE FROM care_routines WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdCareRoutines(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdCareRoutines, targetHouseholdID)
	return err
}

const deleteHouseholdCareTasks = `-- name: DeleteHouseholdCareTasks :exec
DELETE FROM care_tasks WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdCareTasks(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdCareTasks, targetHouseholdID)
	return err
}

const deleteHouseholdCharges = `-- name: DeleteHouseholdCharges :exec
DELETE FROM charges WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdCharges(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdCharges, targetHouseholdID)
	return err
}

const deleteHouseholdContactLinks = `-- name: DeleteHouseholdContactLinks :exec
DELETE FROM household_contacts WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdContactLinks(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdContactLinks, targetHouseholdID)
	return err
}

const deleteHouseholdConversations = `-- name: DeleteHouseholdConversations :exec
DELETE FROM conversations WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdConversations(ctx context.Context, targetHouseholdID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdConversations, targetHouseholdID)
	return err
}

const deleteHouseholdDetectedRequests = `-- name: DeleteHouseholdDetectedRequests :exec
DELETE FROM detected_requests
WHERE detected_requests.household_id = ?1
   OR converted_booking_id IN (SELECT bookings.id FROM bookings WHERE bookings.household_id = ?1)
   OR message_id IN (
	SELECT m.id FROM messages AS m
	JOIN conversations AS c ON c.id = m.conversation_id
	WHERE c.household_id = ?1
   )
`

func (q *Queries) DeleteHouseholdDetectedRequests(ctx context.Context, targetHouseholdID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdDetectedRequests, targetHouseholdID)
	return err
}

const deleteHouseholdMessages = `-- name: DeleteHouseholdMessages :exec
DELETE FROM messages
WHERE conversation_id IN (SELECT id FROM conversations WHERE household_id = ?1)
`

func (q *Queries) DeleteHouseholdMessages(ctx context.Context, targetHouseholdID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdMessages, targetHouseholdID)
	return err
}

const deleteHouseholdOutboundMessages = `-- name: DeleteHouseholdOutboundMessages :exec
DELETE FROM outbound_messages
WHERE detected_request_id IN (
	SELECT dr.id
	FROM detected_requests AS dr
	WHERE dr.household_id = ?1
	   OR dr.converted_booking_id IN (SELECT bookings.id FROM bookings WHERE bookings.household_id = ?1)
	   OR dr.message_id IN (
		SELECT m.id FROM messages AS m
		JOIN conversations AS c ON c.id = m.conversation_id
		WHERE c.household_id = ?1
	   )
)
`

func (q *Queries) DeleteHouseholdOutboundMessages(ctx context.Context, targetHouseholdID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdOutboundMessages, targetHouseholdID)
	return err
}

const deleteHouseholdPaymentAllocations = `-- name: DeleteHouseholdPaymentAllocations :exec
DELETE FROM payment_allocations
WHERE charge_id IN (SELECT id FROM charges WHERE household_id = ?1)
`

func (q *Queries) DeleteHouseholdPaymentAllocations(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdPaymentAllocations, targetHouseholdID)
	return err
}

const deleteHouseholdPetDiets = `-- name: DeleteHouseholdPetDiets :exec
DELETE FROM pet_diets
WHERE pet_id IN (SELECT id FROM pets WHERE household_id = ?1)
`

func (q *Queries) DeleteHouseholdPetDiets(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdPetDiets, targetHouseholdID)
	return err
}

const deleteHouseholdPetMedications = `-- name: DeleteHouseholdPetMedications :exec
DELETE FROM pet_medications
WHERE pet_id IN (SELECT id FROM pets WHERE household_id = ?1)
`

func (q *Queries) DeleteHouseholdPetMedications(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdPetMedications, targetHouseholdID)
	return err
}

const deleteHouseholdPets = `-- name: DeleteHouseholdPets :exec
DELETE FROM pets WHERE household_id = ?1
`

func (q *Queries) DeleteHouseholdPets(ctx context.Context, targetHouseholdID string) error {
	_, err := q.db.ExecContext(ctx, deleteHouseholdPets, targetHouseholdID)
	return err
}

const deleteHouseholdRecord = `-- name: DeleteHouseholdRecord :execrows
DELETE FROM households WHERE id = ?1
`

func (q *Queries) DeleteHouseholdRecord(ctx context.Context, targetHouseholdID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHouseholdRecord, targetHouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listHouseholdContactIDsForDeletion = `-- name: ListHouseholdContactIDsForDeletion :many
SELECT DISTINCT contact_id
FROM household_contacts
WHERE household_id = ?1
`

func (q *Queries) ListHouseholdContactIDsForDeletion(ctx context.Context, targetHouseholdID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdContactIDsForDeletion, targetHouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var contact_id string
		if err := rows.Scan(&contact_id); err != nil {
			return nil, err
		}
		items = append(items, contact_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
