// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package queries

import (
	"context"
	"database/sql"
)

const convertDetectedRequest = `-- name: ConvertDetectedRequest :one
UPDATE detected_requests
SET
	status = 'converted_to_booking',
	converted_booking_id = ?,
	review_notes = ?,
	updated_at = ?
WHERE id = ? AND converted_booking_id IS NULL AND status != 'ignored'
RETURNING id, message_id, household_id, contact_id, detected_service_type, detected_start_at, detected_end_at, confidence, status, converted_booking_id, raw_payload_json, review_notes, created_at, updated_at
`

type ConvertDetectedRequestParams struct {
	ConvertedBookingID sql.NullString `json:"converted_booking_id"`
	ReviewNotes        sql.NullString `json:"review_notes"`
	UpdatedAt          string         `json:"updated_at"`
	ID                 string         `json:"id"`
}

func (q *Queries) ConvertDetectedRequest(ctx context.Context, arg ConvertDetectedRequestParams) (DetectedRequest, error) {
	row := q.db.QueryRowContext(ctx, convertDetectedRequest,
		arg.ConvertedBookingID,
		arg.ReviewNotes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i DetectedRequest
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.HouseholdID,
		&i.ContactID,
		&i.DetectedServiceType,
		&i.DetectedStartAt,
		&i.DetectedEndAt,
		&i.Confidence,
		&i.Status,
		&i.ConvertedBookingID,
		&i.RawPayloadJson,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingSource = `-- name: CreateBookingSource :exec
INSERT INTO booking_sources (
	id,
	booking_id,
	message_id,
	detected_request_id,
	source_note,
	created_at
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBookingSourceParams struct {
	ID                string         `json:"id"`
	BookingID         string         `json:"booking_id"`
	MessageID         sql.NullString `json:"message_id"`
	DetectedRequestID sql.NullString `json:"detected_request_id"`
	SourceNote        sql.NullString `json:"source_note"`
	CreatedAt         string         `json:"created_at"`
}

func (q *Queries) CreateBookingSource(ctx context.Context, arg CreateBookingSourceParams) error {
	_, err := q.db.ExecContext(ctx, createBookingSource,
		arg.ID,
		arg.BookingID,
		arg.MessageID,
		arg.DetectedRequestID,
		arg.SourceNote,
		arg.CreatedAt,
	)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
	id,
	channel,
	external_conversation_id,
	primary_contact_id,
	household_id,
	last_message_at,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, channel, external_conversation_id, primary_contact_id, household_id, last_message_at, created_at, updated_at
`

type CreateConversationParams struct {
	ID                     string         `json:"id"`
	Channel                string         `json:"channel"`
	ExternalConversationID sql.NullString `json:"external_conversation_id"`
	PrimaryContactID       sql.NullString `json:"primary_contact_id"`
	HouseholdID            sql.NullString `json:"household_id"`
	LastMessageAt          sql.NullString `json:"last_message_at"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.Channel,
		arg.ExternalConversationID,
		arg.PrimaryContactID,
		arg.HouseholdID,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalConversationID,
		&i.PrimaryContactID,
		&i.HouseholdID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDetectedRequest = `-- name: CreateDetectedRequest :one
INSERT INTO detected_requests (
	id,
	message_id,
	household_id,
	contact_id,
	detected_service_type,
	detected_start_at,
	detected_end_at,
	confidence,
	status,
	raw_payload_json,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'needs_review', ?, ?, ?)
RETURNING id, message_id, household_id, contact_id, detected_service_type, detected_start_at, detected_end_at, confidence, status, converted_booking_id, raw_payload_json, review_notes, created_at, updated_at
`

type CreateDetectedRequestParams struct {
	ID                  string         `json:"id"`
	MessageID           string         `json:"message_id"`
	HouseholdID         sql.NullString `json:"household_id"`
	ContactID           sql.NullString `json:"contact_id"`
	DetectedServiceType sql.NullString `json:"detected_service_type"`
	DetectedStartAt     sql.NullString `json:"detected_start_at"`
	DetectedEndAt       sql.NullString `json:"detected_end_at"`
	Confidence          string         `json:"confidence"`
	RawPayloadJson      sql.NullString `json:"raw_payload_json"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) CreateDetectedRequest(ctx context.Context, arg CreateDetectedRequestParams) (DetectedRequest, error) {
	row := q.db.QueryRowContext(ctx, createDetectedRequest,
		arg.ID,
		arg.MessageID,
		arg.HouseholdID,
		arg.ContactID,
		arg.DetectedServiceType,
		arg.DetectedStartAt,
		arg.DetectedEndAt,
		arg.Confidence,
		arg.RawPayloadJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DetectedRequest
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.HouseholdID,
		&i.ContactID,
		&i.DetectedServiceType,
		&i.DetectedStartAt,
		&i.DetectedEndAt,
		&i.Confidence,
		&i.Status,
		&i.ConvertedBookingID,
		&i.RawPayloadJson,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
	id,
	conversation_id,
	sender_contact_id,
	direction,
	body,
	sent_at,
	imported_at,
	external_message_id,
	sender_external_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, sender_contact_id, direction, body, sent_at, imported_at, external_message_id, sender_external_id
`

type CreateMessageParams struct {
	ID                string         `json:"id"`
	ConversationID    string         `json:"conversation_id"`
	SenderContactID   sql.NullString `json:"sender_contact_id"`
	Direction         string         `json:"direction"`
	Body              string         `json:"body"`
	SentAt            sql.NullString `json:"sent_at"`
	ImportedAt        string         `json:"imported_at"`
	ExternalMessageID sql.NullString `json:"external_message_id"`
	SenderExternalID  sql.NullString `json:"sender_external_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderContactID,
		arg.Direction,
		arg.Body,
		arg.SentAt,
		arg.ImportedAt,
		arg.ExternalMessageID,
		arg.SenderExternalID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderContactID,
		&i.Direction,
		&i.Body,
		&i.SentAt,
		&i.ImportedAt,
		&i.ExternalMessageID,
		&i.SenderExternalID,
	)
	return i, err
}

const getContactByChannelID = `-- name: GetContactByChannelID :one
SELECT id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
FROM contacts
WHERE
	(? = 'telegram' AND telegram_id = ?)
	OR (? = 'whatsapp' AND whatsapp_id = ?)
LIMIT 1
`

type GetContactByChannelIDParams struct {
	Column1    interface{}    `json:"column_1"`
	TelegramID sql.NullString `json:"telegram_id"`
	Column3    interface{}    `json:"column_3"`
	WhatsappID sql.NullString `json:"whatsapp_id"`
}

func (q *Queries) GetContactByChannelID(ctx context.Context, arg GetContactByChannelIDParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContactByChannelID,
		arg.Column1,
		arg.TelegramID,
		arg.Column3,
		arg.WhatsappID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByExternalID = `-- name: GetConversationByExternalID :one
SELECT id, channel, external_conversation_id, primary_contact_id, household_id, last_message_at, created_at, updated_at
FROM conversations
WHERE channel = ? AND external_conversation_id = ?
ORDER BY created_at
LIMIT 1
`

type GetConversationByExternalIDParams struct {
	Channel                string         `json:"channel"`
	ExternalConversationID sql.NullString `json:"external_conversation_id"`
}

func (q *Queries) GetConversationByExternalID(ctx context.Context, arg GetConversationByExternalIDParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByExternalID, arg.Channel, arg.ExternalConversationID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalConversationID,
		&i.PrimaryContactID,
		&i.HouseholdID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDetectedRequestByMessage = `-- name: GetDetectedRequestByMessage :one
SELECT id, message_id, household_id, contact_id, detected_service_type, detected_start_at, detected_end_at, confidence, status, converted_booking_id, raw_payload_json, review_notes, created_at, updated_at
FROM detected_requests
WHERE message_id = ?
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetDetectedRequestByMessage(ctx context.Context, messageID string) (DetectedRequest, error) {
	row := q.db.QueryRowContext(ctx, getDetectedRequestByMessage, messageID)
	var i DetectedRequest
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.HouseholdID,
		&i.ContactID,
		&i.DetectedServiceType,
		&i.DetectedStartAt,
		&i.DetectedEndAt,
		&i.Confidence,
		&i.Status,
		&i.ConvertedBookingID,
		&i.RawPayloadJson,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDetectedRequestDetail = `-- name: GetDetectedRequestDetail :one
SELECT
	dr.id, dr.message_id, dr.household_id, dr.contact_id, dr.detected_service_type, dr.detected_start_at, dr.detected_end_at, dr.confidence, dr.status, dr.converted_booking_id, dr.raw_payload_json, dr.review_notes, dr.created_at, dr.updated_at,
	m.body AS message_body,
	m.sent_at AS message_sent_at,
	m.external_message_id,
	m.sender_external_id,
	c.channel,
	c.external_conversation_id,
	b.start_at AS converted_booking_start_at,
	b.household_id AS converted_booking_household_id,
	COALESCE(h.display_name, '') AS household_name,
	COALESCE(ct.display_name, '') AS contact_name
FROM detected_requests AS dr
JOIN messages AS m ON m.id = dr.message_id
JOIN conversations AS c ON c.id = m.conversation_id
LEFT JOIN households AS h ON h.id = dr.household_id
LEFT JOIN contacts AS ct ON ct.id = dr.contact_id
LEFT JOIN bookings AS b ON b.id = dr.converted_booking_id
WHERE dr.id = ?
`

type GetDetectedRequestDetailRow struct {
	ID                          string         `json:"id"`
	MessageID                   string         `json:"message_id"`
	HouseholdID                 sql.NullString `json:"household_id"`
	ContactID                   sql.NullString `json:"contact_id"`
	DetectedServiceType         sql.NullString `json:"detected_service_type"`
	DetectedStartAt             sql.NullString `json:"detected_start_at"`
	DetectedEndAt               sql.NullString `json:"detected_end_at"`
	Confidence                  string         `json:"confidence"`
	Status                      string         `json:"status"`
	ConvertedBookingID          sql.NullString `json:"converted_booking_id"`
	RawPayloadJson              sql.NullString `json:"raw_payload_json"`
	ReviewNotes                 sql.NullString `json:"review_notes"`
	CreatedAt                   string         `json:"created_at"`
	UpdatedAt                   string         `json:"updated_at"`
	MessageBody                 string         `json:"message_body"`
	MessageSentAt               sql.NullString `json:"message_sent_at"`
	ExternalMessageID           sql.NullString `json:"external_message_id"`
	SenderExternalID            sql.NullString `json:"sender_external_id"`
	Channel                     string         `json:"channel"`
	ExternalConversationID      sql.NullString `json:"external_conversation_id"`
	ConvertedBookingStartAt     sql.NullString `json:"converted_booking_start_at"`
	ConvertedBookingHouseholdID sql.NullString `json:"converted_booking_household_id"`
	HouseholdName               string         `json:"household_name"`
	ContactName                 string         `json:"contact_name"`
}

func (q *Queries) GetDetectedRequestDetail(ctx context.Context, id string) (GetDetectedRequestDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getDetectedRequestDetail, id)
	var i GetDetectedRequestDetailRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.HouseholdID,
		&i.ContactID,
		&i.DetectedServiceType,
		&i.DetectedStartAt,
		&i.DetectedEndAt,
		&i.Confidence,
		&i.Status,
		&i.ConvertedBookingID,
		&i.RawPayloadJson,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageBody,
		&i.MessageSentAt,
		&i.ExternalMessageID,
		&i.SenderExternalID,
		&i.Channel,
		&i.ExternalConversationID,
		&i.ConvertedBookingStartAt,
		&i.ConvertedBookingHouseholdID,
		&i.HouseholdName,
		&i.ContactName,
	)
	return i, err
}

const getImportedMessageByExternalID = `-- name: GetImportedMessageByExternalID :one
SELECT m.id, m.conversation_id, m.sender_contact_id, m.direction, m.body, m.sent_at, m.imported_at, m.external_message_id, m.sender_external_id
FROM messages AS m
JOIN conversations AS c ON c.id = m.conversation_id
WHERE c.channel = ? AND c.external_conversation_id = ? AND m.external_message_id = ?
ORDER BY m.imported_at
LIMIT 1
`

type GetImportedMessageByExternalIDParams struct {
	Channel                string         `json:"channel"`
	ExternalConversationID sql.NullString `json:"external_conversation_id"`
	ExternalMessageID      sql.NullString `json:"external_message_id"`
}

func (q *Queries) GetImportedMessageByExternalID(ctx context.Context, arg GetImportedMessageByExternalIDParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getImportedMessageByExternalID, arg.Channel, arg.ExternalConversationID, arg.ExternalMessageID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderContactID,
		&i.Direction,
		&i.Body,
		&i.SentAt,
		&i.ImportedAt,
		&i.ExternalMessageID,
		&i.SenderExternalID,
	)
	return i, err
}

const getPrimaryHouseholdForContact = `-- name: GetPrimaryHouseholdForContact :one
SELECT h.id, h.display_name, h.address_line1, h.address_line2, h.neighborhood, h.city, h.timezone, h.notes, h.active, h.created_at, h.updated_at
FROM households AS h
JOIN household_contacts AS hc ON hc.household_id = h.id
WHERE hc.contact_id = ? AND h.active = 1
ORDER BY hc.is_primary DESC, hc.created_at
LIMIT 1
`

func (q *Queries) GetPrimaryHouseholdForContact(ctx context.Context, contactID string) (Household, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryHouseholdForContact, contactID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Neighborhood,
		&i.City,
		&i.Timezone,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkContactTelegramIdentity = `-- name: LinkContactTelegramIdentity :one
UPDATE contacts
SET telegram_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
`

type LinkContactTelegramIdentityParams struct {
	TelegramID sql.NullString `json:"telegram_id"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) LinkContactTelegramIdentity(ctx context.Context, arg LinkContactTelegramIdentityParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, linkContactTelegramIdentity, arg.TelegramID, arg.UpdatedAt, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkContactWhatsappIdentity = `-- name: LinkContactWhatsappIdentity :one
UPDATE contacts
SET whatsapp_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, display_name, phone, whatsapp_id, telegram_id, email, notes, active, created_at, updated_at
`

type LinkContactWhatsappIdentityParams struct {
	WhatsappID sql.NullString `json:"whatsapp_id"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) LinkContactWhatsappIdentity(ctx context.Context, arg LinkContactWhatsappIdentityParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, linkContactWhatsappIdentity, arg.WhatsappID, arg.UpdatedAt, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.WhatsappID,
		&i.TelegramID,
		&i.Email,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkConversationContactContext = `-- name: LinkConversationContactContext :exec
UPDATE conversations
SET primary_contact_id = ?, household_id = ?, updated_at = ?
WHERE conversations.id = (
	SELECT messages.conversation_id
	FROM messages
	WHERE messages.id = ?
)
`

type LinkConversationContactContextParams struct {
	PrimaryContactID sql.NullString `json:"primary_contact_id"`
	HouseholdID      sql.NullString `json:"household_id"`
	UpdatedAt        string         `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) LinkConversationContactContext(ctx context.Context, arg LinkConversationContactContextParams) error {
	_, err := q.db.ExecContext(ctx, linkConversationContactContext,
		arg.PrimaryContactID,
		arg.HouseholdID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const linkDetectedRequestContext = `-- name: LinkDetectedRequestContext :exec
UPDATE detected_requests
SET contact_id = ?, household_id = ?, updated_at = ?
WHERE id = ?
`

type LinkDetectedRequestContextParams struct {
	ContactID   sql.NullString `json:"contact_id"`
	HouseholdID sql.NullString `json:"household_id"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) LinkDetectedRequestContext(ctx context.Context, arg LinkDetectedRequestContextParams) error {
	_, err := q.db.ExecContext(ctx, linkDetectedRequestContext,
		arg.ContactID,
		arg.HouseholdID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const linkMessageSenderContact = `-- name: LinkMessageSenderContact :exec
UPDATE messages
SET sender_contact_id = ?
WHERE id = ?
`

type LinkMessageSenderContactParams struct {
	SenderContactID sql.NullString `json:"sender_contact_id"`
	ID              string         `json:"id"`
}

func (q *Queries) LinkMessageSenderContact(ctx context.Context, arg LinkMessageSenderContactParams) error {
	_, err := q.db.ExecContext(ctx, linkMessageSenderContact, arg.SenderContactID, arg.ID)
	return err
}

const listDetectedRequests = `-- name: ListDetectedRequests :many
SELECT
	dr.id, dr.message_id, dr.household_id, dr.contact_id, dr.detected_service_type, dr.detected_start_at, dr.detected_end_at, dr.confidence, dr.status, dr.converted_booking_id, dr.raw_payload_json, dr.review_notes, dr.created_at, dr.updated_at,
	m.body AS message_body,
	m.sent_at AS message_sent_at,
	m.external_message_id,
	m.sender_external_id,
	c.channel,
	c.external_conversation_id,
	b.start_at AS converted_booking_start_at,
	b.household_id AS converted_booking_household_id,
	COALESCE(h.display_name, '') AS household_name,
	COALESCE(ct.display_name, '') AS contact_name
FROM detected_requests AS dr
JOIN messages AS m ON m.id = dr.message_id
JOIN conversations AS c ON c.id = m.conversation_id
LEFT JOIN households AS h ON h.id = dr.household_id
LEFT JOIN contacts AS ct ON ct.id = dr.contact_id
LEFT JOIN bookings AS b ON b.id = dr.converted_booking_id
WHERE (? = '' OR dr.status = ?)
ORDER BY dr.created_at DESC
`

type ListDetectedRequestsParams struct {
	Column1 interface{} `json:"column_1"`
	Status  string      `json:"status"`
}

type ListDetectedRequestsRow struct {
	ID                          string         `json:"id"`
	MessageID                   string         `json:"message_id"`
	HouseholdID                 sql.NullString `json:"household_id"`
	ContactID                   sql.NullString `json:"contact_id"`
	DetectedServiceType         sql.NullString `json:"detected_service_type"`
	DetectedStartAt             sql.NullString `json:"detected_start_at"`
	DetectedEndAt               sql.NullString `json:"detected_end_at"`
	Confidence                  string         `json:"confidence"`
	Status                      string         `json:"status"`
	ConvertedBookingID          sql.NullString `json:"converted_booking_id"`
	RawPayloadJson              sql.NullString `json:"raw_payload_json"`
	ReviewNotes                 sql.NullString `json:"review_notes"`
	CreatedAt                   string         `json:"created_at"`
	UpdatedAt                   string         `json:"updated_at"`
	MessageBody                 string         `json:"message_body"`
	MessageSentAt               sql.NullString `json:"message_sent_at"`
	ExternalMessageID           sql.NullString `json:"external_message_id"`
	SenderExternalID            sql.NullString `json:"sender_external_id"`
	Channel                     string         `json:"channel"`
	ExternalConversationID      sql.NullString `json:"external_conversation_id"`
	ConvertedBookingStartAt     sql.NullString `json:"converted_booking_start_at"`
	ConvertedBookingHouseholdID sql.NullString `json:"converted_booking_household_id"`
	HouseholdName               string         `json:"household_name"`
	ContactName                 string         `json:"contact_name"`
}

func (q *Queries) ListDetectedRequests(ctx context.Context, arg ListDetectedRequestsParams) ([]ListDetectedRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDetectedRequests, arg.Column1, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetectedRequestsRow
	for rows.Next() {
		var i ListDetectedRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.HouseholdID,
			&i.ContactID,
			&i.DetectedServiceType,
			&i.DetectedStartAt,
			&i.DetectedEndAt,
			&i.Confidence,
			&i.Status,
			&i.ConvertedBookingID,
			&i.RawPayloadJson,
			&i.ReviewNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageBody,
			&i.MessageSentAt,
			&i.ExternalMessageID,
			&i.SenderExternalID,
			&i.Channel,
			&i.ExternalConversationID,
			&i.ConvertedBookingStartAt,
			&i.ConvertedBookingHouseholdID,
			&i.HouseholdName,
			&i.ContactName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationFromImport = `-- name: UpdateConversationFromImport :one
UPDATE conversations
SET
	primary_contact_id = COALESCE(primary_contact_id, ?),
	household_id = COALESCE(household_id, ?),
	last_message_at = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, channel, external_conversation_id, primary_contact_id, household_id, last_message_at, created_at, updated_at
`

type UpdateConversationFromImportParams struct {
	PrimaryContactID sql.NullString `json:"primary_contact_id"`
	HouseholdID      sql.NullString `json:"household_id"`
	LastMessageAt    sql.NullString `json:"last_message_at"`
	UpdatedAt        string         `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateConversationFromImport(ctx context.Context, arg UpdateConversationFromImportParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversationFromImport,
		arg.PrimaryContactID,
		arg.HouseholdID,
		arg.LastMessageAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalConversationID,
		&i.PrimaryContactID,
		&i.HouseholdID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDetectedRequestStatus = `-- name: UpdateDetectedRequestStatus :one
UPDATE detected_requests
SET status = ?, review_notes = ?, updated_at = ?
WHERE id = ?
RETURNING id, message_id, household_id, contact_id, detected_service_type, detected_start_at, detected_end_at, confidence, status, converted_booking_id, raw_payload_json, review_notes, created_at, updated_at
`

type UpdateDetectedRequestStatusParams struct {
	Status      string         `json:"status"`
	ReviewNotes sql.NullString `json:"review_notes"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateDetectedRequestStatus(ctx context.Context, arg UpdateDetectedRequestStatusParams) (DetectedRequest, error) {
	row := q.db.QueryRowContext(ctx, updateDetectedRequestStatus,
		arg.Status,
		arg.ReviewNotes,
		arg.UpdatedAt,
		arg.ID,
	)
	var i DetectedRequest
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.HouseholdID,
		&i.ContactID,
		&i.DetectedServiceType,
		&i.DetectedStartAt,
		&i.DetectedEndAt,
		&i.Confidence,
		&i.Status,
		&i.ConvertedBookingID,
		&i.RawPayloadJson,
		&i.ReviewNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
