// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type Booking struct {
	ID                   string         `json:"id"`
	HouseholdID          string         `json:"household_id"`
	ServiceType          string         `json:"service_type"`
	Status               string         `json:"status"`
	StartAt              string         `json:"start_at"`
	EndAt                sql.NullString `json:"end_at"`
	LocationType         string         `json:"location_type"`
	AddressSnapshot      sql.NullString `json:"address_snapshot"`
	RequestedByContactID sql.NullString `json:"requested_by_contact_id"`
	AssignedStaffID      sql.NullString `json:"assigned_staff_id"`
	Source               string         `json:"source"`
	Notes                sql.NullString `json:"notes"`
	CompletedAt          sql.NullString `json:"completed_at"`
	CancelledAt          sql.NullString `json:"cancelled_at"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

type BookingPet struct {
	BookingID string         `json:"booking_id"`
	PetID     string         `json:"pet_id"`
	Notes     sql.NullString `json:"notes"`
}

type BookingSource struct {
	ID                string         `json:"id"`
	BookingID         string         `json:"booking_id"`
	MessageID         sql.NullString `json:"message_id"`
	DetectedRequestID sql.NullString `json:"detected_request_id"`
	SourceNote        sql.NullString `json:"source_note"`
	CreatedAt         string         `json:"created_at"`
}

type CareRoutine struct {
	ID           string         `json:"id"`
	HouseholdID  string         `json:"household_id"`
	PetID        sql.NullString `json:"pet_id"`
	TaskType     string         `json:"task_type"`
	Title        string         `json:"title"`
	Instructions sql.NullString `json:"instructions"`
	ScheduleNote sql.NullString `json:"schedule_note"`
	Active       int64          `json:"active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type CareTask struct {
	ID                 string         `json:"id"`
	BookingID          sql.NullString `json:"booking_id"`
	HouseholdID        string         `json:"household_id"`
	PetID              sql.NullString `json:"pet_id"`
	TaskType           string         `json:"task_type"`
	Title              string         `json:"title"`
	Instructions       sql.NullString `json:"instructions"`
	DueAt              sql.NullString `json:"due_at"`
	Status             string         `json:"status"`
	AssignedStaffID    sql.NullString `json:"assigned_staff_id"`
	CompletedAt        sql.NullString `json:"completed_at"`
	CompletedByStaffID sql.NullString `json:"completed_by_staff_id"`
	SkippedReason      sql.NullString `json:"skipped_reason"`
	CreatedAt          string         `json:"created_at"`
	UpdatedAt          string         `json:"updated_at"`
}

type Charge struct {
	ID          string         `json:"id"`
	HouseholdID string         `json:"household_id"`
	BookingID   sql.NullString `json:"booking_id"`
	Description string         `json:"description"`
	AmountMinor int64          `json:"amount_minor"`
	Currency    string         `json:"currency"`
	Status      string         `json:"status"`
	DueDate     sql.NullString `json:"due_date"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type Contact struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	WhatsappID  sql.NullString `json:"whatsapp_id"`
	TelegramID  sql.NullString `json:"telegram_id"`
	Email       sql.NullString `json:"email"`
	Notes       sql.NullString `json:"notes"`
	Active      int64          `json:"active"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type ContactChannelIdentity struct {
	ID             string `json:"id"`
	ContactID      string `json:"contact_id"`
	Channel        string `json:"channel"`
	ExternalUserID string `json:"external_user_id"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type Conversation struct {
	ID                     string         `json:"id"`
	Channel                string         `json:"channel"`
	ExternalConversationID sql.NullString `json:"external_conversation_id"`
	PrimaryContactID       sql.NullString `json:"primary_contact_id"`
	HouseholdID            sql.NullString `json:"household_id"`
	LastMessageAt          sql.NullString `json:"last_message_at"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type DetectedRequest struct {
	ID                  string         `json:"id"`
	MessageID           string         `json:"message_id"`
	HouseholdID         sql.NullString `json:"household_id"`
	ContactID           sql.NullString `json:"contact_id"`
	DetectedServiceType sql.NullString `json:"detected_service_type"`
	DetectedStartAt     sql.NullString `json:"detected_start_at"`
	DetectedEndAt       sql.NullString `json:"detected_end_at"`
	Confidence          string         `json:"confidence"`
	Status              string         `json:"status"`
	ConvertedBookingID  sql.NullString `json:"converted_booking_id"`
	RawPayloadJson      sql.NullString `json:"raw_payload_json"`
	ReviewNotes         sql.NullString `json:"review_notes"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type Household struct {
	ID           string         `json:"id"`
	DisplayName  string         `json:"display_name"`
	AddressLine1 sql.NullString `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	Neighborhood sql.NullString `json:"neighborhood"`
	City         sql.NullString `json:"city"`
	Timezone     sql.NullString `json:"timezone"`
	Notes        sql.NullString `json:"notes"`
	Active       int64          `json:"active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type HouseholdContact struct {
	HouseholdID string         `json:"household_id"`
	ContactID   string         `json:"contact_id"`
	Role        string         `json:"role"`
	IsPrimary   int64          `json:"is_primary"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   string         `json:"created_at"`
}

type Message struct {
	ID                string         `json:"id"`
	ConversationID    string         `json:"conversation_id"`
	SenderContactID   sql.NullString `json:"sender_contact_id"`
	Direction         string         `json:"direction"`
	Body              string         `json:"body"`
	SentAt            sql.NullString `json:"sent_at"`
	ImportedAt        string         `json:"imported_at"`
	ExternalMessageID sql.NullString `json:"external_message_id"`
	SenderExternalID  sql.NullString `json:"sender_external_id"`
}

type OutboundMessage struct {
	ID                  string         `json:"id"`
	DetectedRequestID   string         `json:"detected_request_id"`
	Channel             string         `json:"channel"`
	RecipientExternalID string         `json:"recipient_external_id"`
	TemplateKey         string         `json:"template_key"`
	Body                string         `json:"body"`
	Status              string         `json:"status"`
	Attempts            int64          `json:"attempts"`
	LastError           sql.NullString `json:"last_error"`
	CreatedAt           string         `json:"created_at"`
	SentAt              sql.NullString `json:"sent_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type Payment struct {
	ID             string         `json:"id"`
	PayerContactID sql.NullString `json:"payer_contact_id"`
	ReceivedAt     string         `json:"received_at"`
	AmountMinor    int64          `json:"amount_minor"`
	Currency       string         `json:"currency"`
	Method         string         `json:"method"`
	Reference      sql.NullString `json:"reference"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type PaymentAllocation struct {
	ID          string `json:"id"`
	PaymentID   string `json:"payment_id"`
	ChargeID    string `json:"charge_id"`
	AmountMinor int64  `json:"amount_minor"`
	CreatedAt   string `json:"created_at"`
}

type PaymentReceipt struct {
	ID            string `json:"id"`
	PaymentID     string `json:"payment_id"`
	ReceiptNumber string `json:"receipt_number"`
	SnapshotJson  string `json:"snapshot_json"`
	IssuedAt      string `json:"issued_at"`
	CreatedAt     string `json:"created_at"`
}

type Pet struct {
	ID            string         `json:"id"`
	HouseholdID   string         `json:"household_id"`
	Name          string         `json:"name"`
	Species       string         `json:"species"`
	Breed         sql.NullString `json:"breed"`
	Size          sql.NullString `json:"size"`
	Sex           sql.NullString `json:"sex"`
	Birthdate     sql.NullString `json:"birthdate"`
	ColorMarkings sql.NullString `json:"color_markings"`
	BehaviorNotes sql.NullString `json:"behavior_notes"`
	MedicalNotes  sql.NullString `json:"medical_notes"`
	FeedingNotes  sql.NullString `json:"feeding_notes"`
	VetNotes      sql.NullString `json:"vet_notes"`
	Active        int64          `json:"active"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type PetDiet struct {
	ID           string         `json:"id"`
	PetID        string         `json:"pet_id"`
	FoodName     sql.NullString `json:"food_name"`
	Amount       sql.NullString `json:"amount"`
	ScheduleNote sql.NullString `json:"schedule_note"`
	Instructions sql.NullString `json:"instructions"`
	Active       int64          `json:"active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type PetMedication struct {
	ID           string         `json:"id"`
	PetID        string         `json:"pet_id"`
	Name         string         `json:"name"`
	Dosage       sql.NullString `json:"dosage"`
	Instructions sql.NullString `json:"instructions"`
	ScheduleNote sql.NullString `json:"schedule_note"`
	Active       int64          `json:"active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type StaffMember struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	Role        string         `json:"role"`
	Active      int64          `json:"active"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}
