// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbound_messages.sql

package queries

import (
	"context"
	"database/sql"
)

const createOutboundMessage = `-- name: CreateOutboundMessage :one
INSERT INTO outbound_messages (
	id,
	detected_request_id,
	channel,
	recipient_external_id,
	template_key,
	body,
	status,
	attempts,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, 'pending', 0, ?, ?)
RETURNING id, detected_request_id, channel, recipient_external_id, template_key, body, status, attempts, last_error, created_at, sent_at, updated_at
`

type CreateOutboundMessageParams struct {
	ID                  string `json:"id"`
	DetectedRequestID   string `json:"detected_request_id"`
	Channel             string `json:"channel"`
	RecipientExternalID string `json:"recipient_external_id"`
	TemplateKey         string `json:"template_key"`
	Body                string `json:"body"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

func (q *Queries) CreateOutboundMessage(ctx context.Context, arg CreateOutboundMessageParams) (OutboundMessage, error) {
	row := q.db.QueryRowContext(ctx, createOutboundMessage,
		arg.ID,
		arg.DetectedRequestID,
		arg.Channel,
		arg.RecipientExternalID,
		arg.TemplateKey,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OutboundMessage
	err := row.Scan(
		&i.ID,
		&i.DetectedRequestID,
		&i.Channel,
		&i.RecipientExternalID,
		&i.TemplateKey,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundMessage = `-- name: GetOutboundMessage :one
SELECT id, detected_request_id, channel, recipient_external_id, template_key, body, status, attempts, last_error, created_at, sent_at, updated_at FROM outbound_messages WHERE id = ?
`

func (q *Queries) GetOutboundMessage(ctx context.Context, id string) (OutboundMessage, error) {
	row := q.db.QueryRowContext(ctx, getOutboundMessage, id)
	var i OutboundMessage
	err := row.Scan(
		&i.ID,
		&i.DetectedRequestID,
		&i.Channel,
		&i.RecipientExternalID,
		&i.TemplateKey,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingOutboundMessageForRequest = `-- name: GetPendingOutboundMessageForRequest :one
SELECT id, detected_request_id, channel, recipient_external_id, template_key, body, status, attempts, last_error, created_at, sent_at, updated_at
FROM outbound_messages
WHERE detected_request_id = ? AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingOutboundMessageForRequest(ctx context.Context, detectedRequestID string) (OutboundMessage, error) {
	row := q.db.QueryRowContext(ctx, getPendingOutboundMessageForRequest, detectedRequestID)
	var i OutboundMessage
	err := row.Scan(
		&i.ID,
		&i.DetectedRequestID,
		&i.Channel,
		&i.RecipientExternalID,
		&i.TemplateKey,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutboundMessages = `-- name: ListOutboundMessages :many
SELECT id, detected_request_id, channel, recipient_external_id, template_key, body, status, attempts, last_error, created_at, sent_at, updated_at
FROM outbound_messages
WHERE (?1 = '' OR status = ?1)
  AND (?2 = '' OR detected_request_id = ?2)
ORDER BY created_at DESC
LIMIT ?3
`

type ListOutboundMessagesParams struct {
	StatusFilter  interface{} `json:"status_filter"`
	RequestFilter interface{} `json:"request_filter"`
	ResultLimit   int64       `json:"result_limit"`
}

func (q *Queries) ListOutboundMessages(ctx context.Context, arg ListOutboundMessagesParams) ([]OutboundMessage, error) {
	rows, err := q.db.QueryContext(ctx, listOutboundMessages, arg.StatusFilter, arg.RequestFilter, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboundMessage
	for rows.Next() {
		var i OutboundMessage
		if err := rows.Scan(
			&i.ID,
			&i.DetectedRequestID,
			&i.Channel,
			&i.RecipientExternalID,
			&i.TemplateKey,
			&i.Body,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboundMessageFailed = `-- name: MarkOutboundMessageFailed :one
UPDATE outbound_messages
SET status = 'failed', attempts = attempts + 1, last_error = ?, updated_at = ?
WHERE id = ? AND status IN ('pending', 'failed')
RETURNING id, detected_request_id, channel, recipient_external_id, template_key, body, status, attempts, last_error, created_at, sent_at, updated_at
`

type MarkOutboundMessageFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) MarkOutboundMessageFailed(ctx context.Context, arg MarkOutboundMessageFailedParams) (OutboundMessage, error) {
	row := q.db.QueryRowContext(ctx, markOutboundMessageFailed, arg.LastError, arg.UpdatedAt, arg.ID)
	var i OutboundMessage
	err := row.Scan(
		&i.ID,
		&i.DetectedRequestID,
		&i.Channel,
		&i.RecipientExternalID,
		&i.TemplateKey,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboundMessageSent = `-- name: MarkOutboundMessageSent :one
UPDATE outbound_messages
SET status = 'sent', attempts = attempts + 1, last_error = NULL,
	sent_at = ?, updated_at = ?
WHERE id = ? AND status IN ('pending', 'failed')
RETURNING id, detected_request_id, channel, recipient_external_id, template_key, body, status, attempts, last_error, created_at, sent_at, updated_at
`

type MarkOutboundMessageSentParams struct {
	SentAt    sql.NullString `json:"sent_at"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) MarkOutboundMessageSent(ctx context.Context, arg MarkOutboundMessageSentParams) (OutboundMessage, error) {
	row := q.db.QueryRowContext(ctx, markOutboundMessageSent, arg.SentAt, arg.UpdatedAt, arg.ID)
	var i OutboundMessage
	err := row.Scan(
		&i.ID,
		&i.DetectedRequestID,
		&i.Channel,
		&i.RecipientExternalID,
		&i.TemplateKey,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}
