// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package queries

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
	id,
	payer_contact_id,
	received_at,
	amount_minor,
	currency,
	method,
	reference,
	notes,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, payer_contact_id, received_at, amount_minor, currency, method, reference, notes, created_at, updated_at
`

type CreatePaymentParams struct {
	ID             string         `json:"id"`
	PayerContactID sql.NullString `json:"payer_contact_id"`
	ReceivedAt     string         `json:"received_at"`
	AmountMinor    int64          `json:"amount_minor"`
	Currency       string         `json:"currency"`
	Method         string         `json:"method"`
	Reference      sql.NullString `json:"reference"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.PayerContactID,
		arg.ReceivedAt,
		arg.AmountMinor,
		arg.Currency,
		arg.Method,
		arg.Reference,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PayerContactID,
		&i.ReceivedAt,
		&i.AmountMinor,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentAllocation = `-- name: CreatePaymentAllocation :one
INSERT INTO payment_allocations (
	id,
	payment_id,
	charge_id,
	amount_minor,
	created_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, payment_id, charge_id, amount_minor, created_at
`

type CreatePaymentAllocationParams struct {
	ID          string `json:"id"`
	PaymentID   string `json:"payment_id"`
	ChargeID    string `json:"charge_id"`
	AmountMinor int64  `json:"amount_minor"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) (PaymentAllocation, error) {
	row := q.db.QueryRowContext(ctx, createPaymentAllocation,
		arg.ID,
		arg.PaymentID,
		arg.ChargeID,
		arg.AmountMinor,
		arg.CreatedAt,
	)
	var i PaymentAllocation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ChargeID,
		&i.AmountMinor,
		&i.CreatedAt,
	)
	return i, err
}

const getAllocatedTotalForCharge = `-- name: GetAllocatedTotalForCharge :one
SELECT CAST(COALESCE(SUM(amount_minor), 0) AS INTEGER)
FROM payment_allocations
WHERE charge_id = ?
`

func (q *Queries) GetAllocatedTotalForCharge(ctx context.Context, chargeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllocatedTotalForCharge, chargeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, payer_contact_id, received_at, amount_minor, currency, method, reference, notes, created_at, updated_at
FROM payments
WHERE id = ?
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PayerContactID,
		&i.ReceivedAt,
		&i.AmountMinor,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentAllocations = `-- name: ListPaymentAllocations :many
SELECT id, payment_id, charge_id, amount_minor, created_at
FROM payment_allocations
WHERE payment_id = ?
ORDER BY created_at
`

func (q *Queries) ListPaymentAllocations(ctx context.Context, paymentID string) ([]PaymentAllocation, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentAllocations, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAllocation
	for rows.Next() {
		var i PaymentAllocation
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ChargeID,
			&i.AmountMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, payer_contact_id, received_at, amount_minor, currency, method, reference, notes, created_at, updated_at
FROM payments
ORDER BY received_at DESC, created_at DESC
`

func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PayerContactID,
			&i.ReceivedAt,
			&i.AmountMinor,
			&i.Currency,
			&i.Method,
			&i.Reference,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByContact = `-- name: ListPaymentsByContact :many
SELECT id, payer_contact_id, received_at, amount_minor, currency, method, reference, notes, created_at, updated_at
FROM payments
WHERE payer_contact_id = ?
ORDER BY received_at DESC, created_at DESC
`

func (q *Queries) ListPaymentsByContact(ctx context.Context, payerContactID sql.NullString) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByContact, payerContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PayerContactID,
			&i.ReceivedAt,
			&i.AmountMinor,
			&i.Currency,
			&i.Method,
			&i.Reference,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
