// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment_receipts.sql

package queries

import (
	"context"
	"database/sql"
)

const createPaymentReceipt = `-- name: CreatePaymentReceipt :one
INSERT INTO payment_receipts (
	id,
	payment_id,
	receipt_number,
	snapshot_json,
	issued_at,
	created_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, payment_id, receipt_number, snapshot_json, issued_at, created_at
`

type CreatePaymentReceiptParams struct {
	ID            string `json:"id"`
	PaymentID     string `json:"payment_id"`
	ReceiptNumber string `json:"receipt_number"`
	SnapshotJson  string `json:"snapshot_json"`
	IssuedAt      string `json:"issued_at"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) CreatePaymentReceipt(ctx context.Context, arg CreatePaymentReceiptParams) (PaymentReceipt, error) {
	row := q.db.QueryRowContext(ctx, createPaymentReceipt,
		arg.ID,
		arg.PaymentID,
		arg.ReceiptNumber,
		arg.SnapshotJson,
		arg.IssuedAt,
		arg.CreatedAt,
	)
	var i PaymentReceipt
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ReceiptNumber,
		&i.SnapshotJson,
		&i.IssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentReceipt = `-- name: GetPaymentReceipt :one
SELECT id, payment_id, receipt_number, snapshot_json, issued_at, created_at
FROM payment_receipts
WHERE id = ?
`

func (q *Queries) GetPaymentReceipt(ctx context.Context, id string) (PaymentReceipt, error) {
	row := q.db.QueryRowContext(ctx, getPaymentReceipt, id)
	var i PaymentReceipt
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ReceiptNumber,
		&i.SnapshotJson,
		&i.IssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentReceiptByPayment = `-- name: GetPaymentReceiptByPayment :one
SELECT id, payment_id, receipt_number, snapshot_json, issued_at, created_at
FROM payment_receipts
WHERE payment_id = ?
`

func (q *Queries) GetPaymentReceiptByPayment(ctx context.Context, paymentID string) (PaymentReceipt, error) {
	row := q.db.QueryRowContext(ctx, getPaymentReceiptByPayment, paymentID)
	var i PaymentReceipt
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ReceiptNumber,
		&i.SnapshotJson,
		&i.IssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentReceiptSource = `-- name: GetPaymentReceiptSource :one
SELECT
	p.id AS payment_id,
	p.payer_contact_id,
	c.display_name AS payer_name,
	p.received_at,
	p.amount_minor,
	p.currency,
	p.method,
	p.reference,
	p.notes
FROM payments p
LEFT JOIN contacts c ON c.id = p.payer_contact_id
WHERE p.id = ?
`

type GetPaymentReceiptSourceRow struct {
	PaymentID      string         `json:"payment_id"`
	PayerContactID sql.NullString `json:"payer_contact_id"`
	PayerName      sql.NullString `json:"payer_name"`
	ReceivedAt     string         `json:"received_at"`
	AmountMinor    int64          `json:"amount_minor"`
	Currency       string         `json:"currency"`
	Method         string         `json:"method"`
	Reference      sql.NullString `json:"reference"`
	Notes          sql.NullString `json:"notes"`
}

func (q *Queries) GetPaymentReceiptSource(ctx context.Context, id string) (GetPaymentReceiptSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentReceiptSource, id)
	var i GetPaymentReceiptSourceRow
	err := row.Scan(
		&i.PaymentID,
		&i.PayerContactID,
		&i.PayerName,
		&i.ReceivedAt,
		&i.AmountMinor,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Notes,
	)
	return i, err
}

const listPaymentReceiptAllocationSources = `-- name: ListPaymentReceiptAllocationSources :many
SELECT
	pa.charge_id,
	pa.amount_minor,
	c.description,
	h.display_name AS household_name
FROM payment_allocations pa
JOIN charges c ON c.id = pa.charge_id
JOIN households h ON h.id = c.household_id
WHERE pa.payment_id = ?
ORDER BY pa.created_at, pa.id
`

type ListPaymentReceiptAllocationSourcesRow struct {
	ChargeID      string `json:"charge_id"`
	AmountMinor   int64  `json:"amount_minor"`
	Description   string `json:"description"`
	HouseholdName string `json:"household_name"`
}

func (q *Queries) ListPaymentReceiptAllocationSources(ctx context.Context, paymentID string) ([]ListPaymentReceiptAllocationSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentReceiptAllocationSources, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentReceiptAllocationSourcesRow
	for rows.Next() {
		var i ListPaymentReceiptAllocationSourcesRow
		if err := rows.Scan(
			&i.ChargeID,
			&i.AmountMinor,
			&i.Description,
			&i.HouseholdName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
