// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pets.sql

package queries

import (
	"context"
	"database/sql"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (
	id,
	household_id,
	name,
	species,
	breed,
	size,
	sex,
	birthdate,
	color_markings,
	behavior_notes,
	medical_notes,
	feeding_notes,
	vet_notes,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, household_id, name, species, breed, size, sex, birthdate, color_markings, behavior_notes, medical_notes, feeding_notes, vet_notes, active, created_at, updated_at
`

type CreatePetParams struct {
	ID            string         `json:"id"`
	HouseholdID   string         `json:"household_id"`
	Name          string         `json:"name"`
	Species       string         `json:"species"`
	Breed         sql.NullString `json:"breed"`
	Size          sql.NullString `json:"size"`
	Sex           sql.NullString `json:"sex"`
	Birthdate     sql.NullString `json:"birthdate"`
	ColorMarkings sql.NullString `json:"color_markings"`
	BehaviorNotes sql.NullString `json:"behavior_notes"`
	MedicalNotes  sql.NullString `json:"medical_notes"`
	FeedingNotes  sql.NullString `json:"feeding_notes"`
	VetNotes      sql.NullString `json:"vet_notes"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, createPet,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Size,
		arg.Sex,
		arg.Birthdate,
		arg.ColorMarkings,
		arg.BehaviorNotes,
		arg.MedicalNotes,
		arg.FeedingNotes,
		arg.VetNotes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Size,
		&i.Sex,
		&i.Birthdate,
		&i.ColorMarkings,
		&i.BehaviorNotes,
		&i.MedicalNotes,
		&i.FeedingNotes,
		&i.VetNotes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPet = `-- name: GetPet :one
SELECT id, household_id, name, species, breed, size, sex, birthdate, color_markings, behavior_notes, medical_notes, feeding_notes, vet_notes, active, created_at, updated_at
FROM pets
WHERE id = ?
`

func (q *Queries) GetPet(ctx context.Context, id string) (Pet, error) {
	row := q.db.QueryRowContext(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Size,
		&i.Sex,
		&i.Birthdate,
		&i.ColorMarkings,
		&i.BehaviorNotes,
		&i.MedicalNotes,
		&i.FeedingNotes,
		&i.VetNotes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPets = `-- name: ListPets :many
SELECT id, household_id, name, species, breed, size, sex, birthdate, color_markings, behavior_notes, medical_notes, feeding_notes, vet_notes, active, created_at, updated_at
FROM pets
WHERE active = 1
ORDER BY name
`

func (q *Queries) ListPets(ctx context.Context) ([]Pet, error) {
	rows, err := q.db.QueryContext(ctx, listPets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Size,
			&i.Sex,
			&i.Birthdate,
			&i.ColorMarkings,
			&i.BehaviorNotes,
			&i.MedicalNotes,
			&i.FeedingNotes,
			&i.VetNotes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetsByHousehold = `-- name: ListPetsByHousehold :many
SELECT id, household_id, name, species, breed, size, sex, birthdate, color_markings, behavior_notes, medical_notes, feeding_notes, vet_notes, active, created_at, updated_at
FROM pets
WHERE active = 1 AND household_id = ?
ORDER BY name
`

func (q *Queries) ListPetsByHousehold(ctx context.Context, householdID string) ([]Pet, error) {
	rows, err := q.db.QueryContext(ctx, listPetsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pet
	for rows.Next() {
		var i Pet
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Size,
			&i.Sex,
			&i.Birthdate,
			&i.ColorMarkings,
			&i.BehaviorNotes,
			&i.MedicalNotes,
			&i.FeedingNotes,
			&i.VetNotes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :one
UPDATE pets
SET
	household_id = ?,
	name = ?,
	species = ?,
	breed = ?,
	size = ?,
	sex = ?,
	birthdate = ?,
	color_markings = ?,
	behavior_notes = ?,
	medical_notes = ?,
	feeding_notes = ?,
	vet_notes = ?,
	active = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, household_id, name, species, breed, size, sex, birthdate, color_markings, behavior_notes, medical_notes, feeding_notes, vet_notes, active, created_at, updated_at
`

type UpdatePetParams struct {
	HouseholdID   string         `json:"household_id"`
	Name          string         `json:"name"`
	Species       string         `json:"species"`
	Breed         sql.NullString `json:"breed"`
	Size          sql.NullString `json:"size"`
	Sex           sql.NullString `json:"sex"`
	Birthdate     sql.NullString `json:"birthdate"`
	ColorMarkings sql.NullString `json:"color_markings"`
	BehaviorNotes sql.NullString `json:"behavior_notes"`
	MedicalNotes  sql.NullString `json:"medical_notes"`
	FeedingNotes  sql.NullString `json:"feeding_notes"`
	VetNotes      sql.NullString `json:"vet_notes"`
	Active        int64          `json:"active"`
	UpdatedAt     string         `json:"updated_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, updatePet,
		arg.HouseholdID,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Size,
		arg.Sex,
		arg.Birthdate,
		arg.ColorMarkings,
		arg.BehaviorNotes,
		arg.MedicalNotes,
		arg.FeedingNotes,
		arg.VetNotes,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Size,
		&i.Sex,
		&i.Birthdate,
		&i.ColorMarkings,
		&i.BehaviorNotes,
		&i.MedicalNotes,
		&i.FeedingNotes,
		&i.VetNotes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
