// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddBookingPet(ctx context.Context, arg AddBookingPetParams) error
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateCareTask(ctx context.Context, arg CreateCareTaskParams) (CareTask, error)
	CreateCharge(ctx context.Context, arg CreateChargeParams) (Charge, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) (PaymentAllocation, error)
	CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error)
	CreateStaffMember(ctx context.Context, arg CreateStaffMemberParams) (StaffMember, error)
	DeleteBookingPets(ctx context.Context, bookingID string) error
	GetAllocatedTotalForCharge(ctx context.Context, chargeID string) (int64, error)
	GetBooking(ctx context.Context, id string) (Booking, error)
	GetCareTask(ctx context.Context, id string) (CareTask, error)
	GetCharge(ctx context.Context, id string) (Charge, error)
	GetContact(ctx context.Context, id string) (Contact, error)
	GetHousehold(ctx context.Context, id string) (Household, error)
	GetPayment(ctx context.Context, id string) (Payment, error)
	GetPet(ctx context.Context, id string) (Pet, error)
	GetStaffMember(ctx context.Context, id string) (StaffMember, error)
	LinkHouseholdContact(ctx context.Context, arg LinkHouseholdContactParams) error
	ListBookingPets(ctx context.Context, bookingID string) ([]ListBookingPetsRow, error)
	ListBookings(ctx context.Context) ([]Booking, error)
	ListBookingsByHousehold(ctx context.Context, householdID string) ([]Booking, error)
	ListBookingsByRange(ctx context.Context, arg ListBookingsByRangeParams) ([]Booking, error)
	ListCareTasks(ctx context.Context) ([]CareTask, error)
	ListCareTasksByBooking(ctx context.Context, bookingID sql.NullString) ([]CareTask, error)
	ListCareTasksByHousehold(ctx context.Context, householdID string) ([]CareTask, error)
	ListCareTasksByRange(ctx context.Context, arg ListCareTasksByRangeParams) ([]CareTask, error)
	ListCharges(ctx context.Context) ([]Charge, error)
	ListChargesByHousehold(ctx context.Context, householdID string) ([]Charge, error)
	ListContacts(ctx context.Context) ([]Contact, error)
	ListHouseholdContacts(ctx context.Context, householdID string) ([]ListHouseholdContactsRow, error)
	ListHouseholds(ctx context.Context) ([]Household, error)
	ListOpenCharges(ctx context.Context) ([]Charge, error)
	ListPaymentAllocations(ctx context.Context, paymentID string) ([]PaymentAllocation, error)
	ListPayments(ctx context.Context) ([]Payment, error)
	ListPaymentsByContact(ctx context.Context, payerContactID sql.NullString) ([]Payment, error)
	ListPets(ctx context.Context) ([]Pet, error)
	ListPetsByHousehold(ctx context.Context, householdID string) ([]Pet, error)
	ListStaffMembers(ctx context.Context) ([]StaffMember, error)
	RefreshChargeStatus(ctx context.Context, arg RefreshChargeStatusParams) (Charge, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error)
	UpdateCareTask(ctx context.Context, arg UpdateCareTaskParams) (CareTask, error)
	UpdateCharge(ctx context.Context, arg UpdateChargeParams) (Charge, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error)
	UpdateStaffMember(ctx context.Context, arg UpdateStaffMemberParams) (StaffMember, error)
}

var _ Querier = (*Queries)(nil)
