// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: staff.sql

package queries

import (
	"context"
	"database/sql"
)

const createStaffMember = `-- name: CreateStaffMember :one
INSERT INTO staff_members (
	id,
	display_name,
	phone,
	role,
	created_at,
	updated_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, display_name, phone, role, active, created_at, updated_at
`

type CreateStaffMemberParams struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	Role        string         `json:"role"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreateStaffMember(ctx context.Context, arg CreateStaffMemberParams) (StaffMember, error) {
	row := q.db.QueryRowContext(ctx, createStaffMember,
		arg.ID,
		arg.DisplayName,
		arg.Phone,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i StaffMember
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffMember = `-- name: GetStaffMember :one
SELECT id, display_name, phone, role, active, created_at, updated_at
FROM staff_members
WHERE id = ?
`

func (q *Queries) GetStaffMember(ctx context.Context, id string) (StaffMember, error) {
	row := q.db.QueryRowContext(ctx, getStaffMember, id)
	var i StaffMember
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffMembers = `-- name: ListStaffMembers :many
SELECT id, display_name, phone, role, active, created_at, updated_at
FROM staff_members
WHERE active = 1
ORDER BY display_name
`

func (q *Queries) ListStaffMembers(ctx context.Context) ([]StaffMember, error) {
	rows, err := q.db.QueryContext(ctx, listStaffMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffMember
	for rows.Next() {
		var i StaffMember
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Phone,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffMember = `-- name: UpdateStaffMember :one
UPDATE staff_members
SET
	display_name = ?,
	phone = ?,
	role = ?,
	active = ?,
	updated_at = ?
WHERE id = ?
RETURNING id, display_name, phone, role, active, created_at, updated_at
`

type UpdateStaffMemberParams struct {
	DisplayName string         `json:"display_name"`
	Phone       sql.NullString `json:"phone"`
	Role        string         `json:"role"`
	Active      int64          `json:"active"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateStaffMember(ctx context.Context, arg UpdateStaffMemberParams) (StaffMember, error) {
	row := q.db.QueryRowContext(ctx, updateStaffMember,
		arg.DisplayName,
		arg.Phone,
		arg.Role,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i StaffMember
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
